platform :ios, '8.0'
use_frameworks!
pod 'XCGLogger'
pod 'SQLite.swift',
git: 'https://github.com/stephencelis/SQLite.swift.git'

def import_networking
    pod 'Alamofire'
    pod 'Moya'
end

target 'SwiftPractise' do
    import_networking
end